# 应用服务 WEB 访问端口
server:
  port: 8080
# 应用名称
spring:
  application:
    name: kafka-tutorial

  kafka:
    bootstrap-servers: 1.117.62.185:9093
    producer:
      acks: -1
      batch-size: 15654
      buffer-memory: 33554432
      client-id: zhjc
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
  #    bootstrap-servers: 10.111.39.44:9092,10.111.39.45:9092,10.111.39.46:9092,10.111.39.47:9092,10.111.39.48:9092
      bootstrap-servers: 1.117.62.185:9093
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 3000
#      group-id: zhjc
#      client-id: zhjc
      fetch-min-size: 1
      fetch-max-wait: 3000
      heartbeat-interval: 3000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
     # bootstrap-servers: 10.111.39.44:9092,10.111.39.45:9092,10.111.39.46:9092,10.111.39.47:9092,10.111.39.48:9092
      bootstrap-servers: 1.117.62.185:9093
      max-poll-records: 5000
    listener:
      concurrency: 2
      poll-timeout: 3000


